# Generated by Django 4.2.4 on 2023-09-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mains', 'Mains'), ('Dessert', 'Dessert'), ('Drinks', 'Drinks')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='TransactionDetail',
        ),
    ]
