# Generated by Django 4.2.4 on 2023-10-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_booking_is_approved_booking_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
